function onOpen(){SpreadsheetApp.getUi().createMenu('SJ ONE v3.2').addItem('투자 현재가 갱신','refreshSJOneInvestmentSheet').addItem('운영모드','showSJOneOperatorMode').addItem('관리자모드','showSJOneAdminMode').addToUi();}
function doGet(e){const payload=getSJOneDashboardPayload_();const cb=e&&e.parameter&&e.parameter.callback;if(cb){return ContentService.createTextOutput(cb+'('+JSON.stringify(payload)+');').setMimeType(ContentService.MimeType.JAVASCRIPT);}return ContentService.createTextOutput(JSON.stringify(payload)).setMimeType(ContentService.MimeType.JSON);}
function getSJOneDashboardPayload_(){refreshSJOneInvestmentSheet();return{ok:true,live:true,updatedAt:new Date().toLocaleString('ko-KR'),daily:sheetToObjectsSJONE_('오늘_영업판단',50),onestop:sheetToObjectsSJONE_('기업_원스탑',30),alt:sheetToObjectsSJONE_('대안타깃_DB',50),investments:sheetToObjectsSJONE_('투자_대시보드',20)};}
function refreshSJOneInvestmentSheet(){const ss=SpreadsheetApp.getActiveSpreadsheet();let sh=ss.getSheetByName('투자_대시보드');if(!sh)sh=ss.insertSheet('투자_대시보드');const updated=new Date().toLocaleString('ko-KR');const usdkrw=fetchYahooPrice_('KRW=X');const kodex=fetchNaverPrice_('229200')||fetchYahooPrice_('229200.KQ')||fetchYahooPrice_('229200.KS');const gme=fetchYahooPrice_('GME');const rows=[['name','category','ticker','avg','cur','pnlPct','changePct','judgment','rule','action','source','updatedAt'],makeInvestRow_('KODEX 코스닥150','ETF','229200',16900,kodex,'14,365원 이탈 시 손실 확대 방어 / 16,900원 근처에서는 일부 회수 검토','오늘은 뉴스보다 가격선 확인. 추가매수는 분할만.','Naver/Yahoo',updated),makeInvestRow_('GME','미국주식','GME',28.15,gme,'급등 뉴스가 아닌 가격 회복 여부로 판단. 손실 만회용 무리매수 금지','환율 보조 가격을 분리해서 판단.','Yahoo',updated),makeFxRow_(usdkrw,updated)];sh.clearContents();sh.getRange(1,1,rows.length,rows[0].length).setValues(rows);sh.setFrozenRows(1);return rows;}
function makeInvestRow_(name,cat,ticker,avg,price,rule,action,source,updated){const cur=price&&price.price?Number(price.price):'';const pnl=cur&&avg?((cur-avg)/avg*100):'';const ch=price&&price.changePct!==undefined?price.changePct:'';let judgment='현재가 확인 필요';if(cur&&avg){judgment=pnl>=0?'수익권: 욕심보다 회수 기준 우선':(pnl<=-12?'손실 확대 구간: 방어 우선':'평단 회복 전까지 추격매수 금지');}return[name,cat,ticker,avg,cur,pnl,ch,judgment,rule,action,source,updated];}
function makeFxRow_(fx,updated){const cur=fx&&fx.price?Number(fx.price):'';let judgment='환율 확인 필요';if(cur){judgment=cur>=1450?'원화 약세 강함: 해외주식 체감손익 왜곡 주의':cur>=1400?'원화 약세: 환율효과 분리 판단':'환율 부담 완화 구간';}return['원/달러 환율','환율','USDKRW','',cur,'',fx&&fx.changePct!==undefined?fx.changePct:'',judgment,'환율로 손실이 줄어 보이면 착시 가능성 체크','매도/추가매수 전 환율 영향 분리.','Yahoo',updated];}
function fetchNaverPrice_(code){try{const url='https://polling.finance.naver.com/api/realtime?query=SERVICE_ITEM:'+code;const res=UrlFetchApp.fetch(url,{muteHttpExceptions:true,headers:{'User-Agent':'Mozilla/5.0'}});const txt=res.getContentText();const j=JSON.parse(txt);const d=j.result&&j.result.areas&&j.result.areas[0]&&j.result.areas[0].datas&&j.result.areas[0].datas[0];if(!d)return null;return{price:Number(d.nv),changePct:Number(d.cr)};}catch(e){return null;}}
function fetchYahooPrice_(symbol){try{const url='https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(symbol)+'?range=1d&interval=1m';const res=UrlFetchApp.fetch(url,{muteHttpExceptions:true,headers:{'User-Agent':'Mozilla/5.0'}});const j=JSON.parse(res.getContentText());const meta=j.chart&&j.chart.result&&j.chart.result[0]&&j.chart.result[0].meta;if(!meta)return null;const price=Number(meta.regularMarketPrice||meta.previousClose);const prev=Number(meta.previousClose);const changePct=prev?((price-prev)/prev*100):'';return{price:price,changePct:changePct};}catch(e){return null;}}
function sheetToObjectsSJONE_(name,limit){const ss=SpreadsheetApp.getActiveSpreadsheet();const sh=ss.getSheetByName(name);if(!sh||sh.getLastRow()<2)return[];const values=sh.getDataRange().getDisplayValues();const headers=values[0];return values.slice(1,limit?limit+1:undefined).filter(r=>r.join('').trim()).map(row=>{const o={};headers.forEach((h,i)=>o[h]=row[i]);return o;});}
function showSJOneOperatorMode(){const ss=SpreadsheetApp.getActiveSpreadsheet();const visible=['오늘_영업판단','기업_원스탑','투자_대시보드'];ss.getSheets().forEach(s=>{if(visible.indexOf(s.getName())>=0)s.showSheet();else s.hideSheet();});const first=ss.getSheetByName('오늘_영업판단')||ss.getSheetByName('투자_대시보드')||ss.getSheets()[0];ss.setActiveSheet(first);ss.toast('운영모드 완료','SJ ONE',5);}
function showSJOneAdminMode(){const ss=SpreadsheetApp.getActiveSpreadsheet();ss.getSheets().forEach(s=>s.showSheet());ss.toast('관리자모드 완료','SJ ONE',5);}
