import "./style.css";
const $=(s)=>document.querySelector(s);
const demo={
  updatedAt:new Date().toLocaleString("ko-KR"),
  daily:[
    {decision:"오늘전화",company:"페코텍 후보 타깃군",industry:"반도체 후공정/소부장",role:"품질·자동화SW·국내/해외영업",score:92,why:"반도체 필수 포지션 + 후보 소싱 난이도 높음. 헤드헌터가 개입할 명분이 큼.",action:"오늘 1순위: 유사 기업 10개 채용공고 확인 → 담당자 추정 → 짧은 제안",talk:"반도체 품질/자동화/영업 직무에서 즉시 검토 가능한 후보군을 선별 중입니다. 채용 난이도 높은 포지션만 짧게 논의드리고 싶습니다.",risk:"학력·거리·연봉 기준이 까다로워 후보 검증 질문을 먼저 던져야 함",link:"https://example.com"},
    {decision:"오늘메일",company:"서플러스글로벌 유사 타깃",industry:"반도체 장비/레거시",role:"CRM·이커머스·AI/ML·영업마케팅",score:86,why:"레거시 장비 유통/플랫폼 전환 기업은 IT·영업·데이터 인재 수요가 반복 발생.",action:"메일 우선. 플랫폼/영업마케팅/AI 후보 제안 가능성으로 접근",talk:"장비 유통과 플랫폼 전환을 함께 하는 기업은 CRM·이커머스·AI 인재 매칭이 중요해지고 있습니다.",risk:"이미 거래 헤드헌터가 있을 가능성",link:"https://example.com"},
    {decision:"대기",company:"HL Klemove 유사 전장사",industry:"자동차 전장/SDV",role:"ADAS·IVI 시스템 아키텍트",score:78,why:"고난도 포지션. 적합 후보 수는 적지만 성공 시 단가가 높음.",action:"후보 DB 구축용. 바로 영업보다 후보 확보 먼저",talk:"ADAS-IVI 크로스 도메인 후보군은 시장에 드물어 선제 소싱이 필요합니다.",risk:"너무 어려운 포지션에 시간 과소비 주의",link:"https://example.com"}
  ],
  onestop:[
    {company:"페코텍 후보 타깃군",grade:"A",decision:"오늘전화",signal:"반도체 품질·자동화·영업 경력직 수요",basic:"후공정/패키징 정밀부품·자동화 장비와 연결되는 기업군. 품질/장비SW/영업 포지션이 반복 발생 가능.",market:"HBM·후공정·소부장 투자가 이어질수록 인재 수요가 강해질 가능성이 큼.",review:"실제 평판은 잡플래닛/블라인드/퇴사자 네트워크로 보완 필요.",risk:"학력, 나이, 거리, 연봉 상한이 까다로우면 추천 후 탈락 가능성 증가.",strategy:"첫 통화에서는 '채용공고 봤습니다'보다 '검증된 후보를 짧게 드릴 수 있다'로 접근.",talk:"반도체 품질/자동화/영업 직무에서 필터를 거친 후보자만 짧게 추천드릴 수 있습니다.",link:"https://example.com"},
    {company:"서플러스글로벌 유사 타깃",grade:"A-",decision:"오늘메일",signal:"플랫폼·CRM·AI·영업마케팅 채용 신호",basic:"장비 유통에서 플랫폼/데이터 사업으로 확장하는 기업군.",market:"레거시 장비/부품/마켓플레이스 분야는 글로벌 고객 접점과 IT 인재가 동시에 중요.",review:"조직 변화 속도가 빠를수록 PM/개발/영업마케팅 리더 수요가 발생.",risk:"내부 추천 또는 기존 거래사와 경쟁 가능.",strategy:"후보 추천보다 먼저 '유사 포지션 성공사례' 형태로 접근.",talk:"반도체 장비와 플랫폼 양쪽을 이해하는 후보군은 많지 않아 선제적으로 공유드리고 싶습니다.",link:"https://example.com"}
  ],
  candidates:[
    {name:"이동욱",role:"반도체 검사장비 기구설계",fit:88,risk:"희망연봉 9,500만원 이상 가능성. 처우 협의선 확인 필요.",action:"기구설계/자동화 H/W 포지션은 강점. 가공 자동화 경험 공백은 면접 전 스토리 정리"},
    {name:"김상윤",role:"국내영업/기술영업",fit:73,risk:"기업규모·공백기간·나이 대비 경력 우려",action:"기술영업 실적과 고객사 레벨을 짧게 정리해 추천 메일 보강"},
    {name:"박찬주",role:"품질/데이터 자동화",fit:82,risk:"반도체 직접 경험 여부 확인 필요",action:"품질 DX/수율/자동화 키워드 중심으로 적합도 판단"}
  ],
  investments:[
    {name:"KODEX 코스닥150",type:"ETF",avg:16900,cur:15240,view:"정책 기대감은 유효하지만 평단 회복 전까지 추격매수 금지",rule:"14,365원 이탈 시 손실 확대 방어 / 16,900원 근처에서는 일부 회수 검토",action:"오늘은 뉴스보다 가격선 확인. 추가매수는 분할만."},
    {name:"GME",type:"미국주식",avg:28.15,cur:22.82,view:"이벤트성 변동성이 커서 원화 환율 착시 주의",rule:"급등 뉴스가 아닌 가격 회복 여부로 판단. 손실 만회용 물타기 금지",action:"환율·본주 가격을 분리해서 판단."},
    {name:"원/달러 환율",type:"환율",avg:"-",cur:"체크필요",view:"원화 약세는 해외주식 체감손익을 왜곡할 수 있음",rule:"환율로 손실이 줄어 보이면 착시 가능성 체크",action:"매도/추가매수 전 환율 영향 분리."}
  ],
  assistant:[
    {title:"오늘 금지",body:"앱 수정·자동화 수정·새 기능 기획. 매출 행동 전에는 금지."},
    {title:"오늘 허용",body:"신규 고객사 10개 확인, 담당자 추정, 짧은 메일 5개, 후보자 2명 정리."},
    {title:"판단 기준",body:"돈 되는 포지션인가? 후보가 실제로 있는가? 이번 주 연락할 담당자가 있는가? 세 개가 아니면 보류."}
  ]
};
const state={tab:localStorage.getItem("sjone_tab")||"home",data:demo,apiUrl:localStorage.getItem("sjone_api_url")||"",selectedCompany:null};
const NAV=[["home","홈"],["sales","영업"],["company","기업360"],["sourcing","소싱"],["candidate","후보"],["invest","투자"],["assistant","비서"]];
const esc=x=>String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const b=(t,c="warn")=>`<span class="badge ${c}">${esc(t)}</span>`;
const tone=d=>String(d).includes("오늘전화")?"bad":String(d).includes("오늘메일")?"warn":String(d).includes("대기")?"blue":"neutral";
const kv=(k,v)=>v?`<div class="kv"><b>${esc(k)}</b><span>${esc(v)}</span></div>`:"";
function normDaily(r){return{decision:r.decision||r["결정"],company:r.company||r["회사명"],industry:r.industry||r["산업"],role:r.role||r["직무/포지션"],score:r.score||r["점수"],why:r.why||r["근거요약"],action:r.action||r["추천액션"],talk:r.talk||r["영업멘트"],risk:r.risk||r["리스크"],link:r.link||r["링크"]}}
function normCompany(r){return{company:r.company||r["회사명"],grade:r.grade||r["영업등급"],decision:r.decision||r["추천결정"],signal:r.signal||r["핵심공고/신호"],basic:r.basic||r["기본정보 요약"],market:r.market||r["시장평가/성장성"],review:r.review||r["재직자·경력자 평가 단서"],risk:r.risk||r["리스크/거절가능성"],strategy:r.strategy||r["접근전략"],talk:r.talk||r["추천 영업멘트"],link:r.link||r["근거링크"]}}
function layout(content,notice=""){return`<div class="app"><header class="top"><div><div class="brand">SJ <span>ONE</span> PRODUCTION <span style="font-size:12px;color:#9AA5B5">v3.1</span></div><div class="sub">영업 · 후보 · 소싱 · 투자 · 개인비서 통합 대시보드</div></div><div><button class="btn" data-tab="settings">설정</button> <button class="btn gold" id="refreshBtn">갱신</button></div></header>${notice?`<div class="notice">${esc(notice)}</div>`:""}${content}<nav class="bottom">${NAV.map(([k,l])=>`<button class="${state.tab===k?"on":""}" data-tab="${k}">${l}</button>`).join("")}</nav></div>`}
function stats(){const dy=(state.data.daily||[]).map(normDaily);const co=(state.data.onestop||[]).map(normCompany);return{call:dy.filter(x=>String(x.decision).includes("오늘전화")).length,mail:dy.filter(x=>String(x.decision).includes("오늘메일")).length,a:co.filter(x=>String(x.grade).includes("A")).length,invest:(state.data.investments||[]).length}}
function salesCard(row){const r=normDaily(row);return`<div class="item companyItem" data-company="${esc(r.company)}"><div class="row"><div><div class="company">${esc(r.company)}</div><div class="muted">${esc(r.industry)} · ${esc(r.role)}</div></div>${b(r.decision||"판단",tone(r.decision))}</div><p>${esc(r.why)}</p><div class="scoreBar"><i style="width:${Math.min(100,Number(r.score)||70)}%"></i></div><div class="actionBox">${esc(r.action)}</div>${kv("리스크",r.risk)}${kv("영업멘트",r.talk)}${r.link?`<a class="link" href="${esc(r.link)}" target="_blank">근거 열기</a>`:""}</div>`}
function home(){const dy=state.data.daily||[];const top=normDaily(dy[0]||{});const s=stats();return`<main class="grid"><section class="card hero"><div class="eyebrow">오늘의 최우선 실행</div><h1>${esc(top.company||"오늘 할 기업을 먼저 고르세요")}</h1><div class="row"><div>${b(top.decision||"대기",tone(top.decision))}</div><span class="muted">영업점수 ${esc(top.score||"-")}</span></div><p>${esc(top.why||"시트 연결 전에는 데모 기준으로 표시됩니다.")}</p><div class="actionBox">${esc(top.action||"오늘은 시스템 수정이 아니라 연락부터 실행")}</div></section><section class="grid4"><div class="card"><div class="metric">${s.call}</div><div class="label">오늘 전화</div></div><div class="card"><div class="metric">${s.mail}</div><div class="label">오늘 메일</div></div><div class="card"><div class="metric">${s.a}</div><div class="label">A등급 기업</div></div><div class="card"><div class="metric">${s.invest}</div><div class="label">투자 체크</div></div></section><section class="grid2"><div class="card"><div class="sectionTitle">오늘 행동 순서</div><ol class="todo"><li>오늘전화 기업부터 3개 처리</li><li>기업360에서 리스크와 접근멘트 확인</li><li>담당자 추정 → 짧은 메일/전화</li><li>후보자는 추천 가능/보류/탈락만 판단</li><li>투자는 가격선만 확인하고 감정매매 금지</li></ol></div><div class="card"><div class="sectionTitle">오늘 금지</div><p>앱·자동화·시트 구조를 더 만지는 순간 영업 시간이 사라집니다. 오늘은 돈 되는 행동만 합니다.</p><div class="actionBox">신규고객사 영업 5건 또는 후보자 추천 2건 전까지 시스템 수정 금지</div></div></section><section class="card"><div class="sectionTitle">오늘 영업 TOP</div><div class="list">${dy.map(salesCard).join("")}</div></section></main>`}
function sales(){return`<main class="grid"><section class="card"><div class="sectionTitle">신규고객사 Sales Radar</div><p>결정 기준은 단순합니다. 오늘전화, 오늘메일, 대기. 나머지는 버립니다.</p></section><section class="list">${(state.data.daily||[]).map(salesCard).join("")}</section></main>`}
function company(){const rows=(state.data.onestop||[]).map(normCompany);const sel=state.selectedCompany||(rows[0]&&rows[0].company);const r=rows.find(x=>x.company===sel)||rows[0];if(!r)return`<main><div class="card">기업 데이터 없음</div></main>`;return`<main class="grid"><section class="card hero"><div class="row"><div><div class="eyebrow">Company 360</div><h1>${esc(r.company)}</h1></div>${b((r.grade||"-")+" · "+(r.decision||"-"),String(r.grade).includes("A")?"bad":"warn")}</div><div class="actionBox">${esc(r.strategy)}</div></section><section class="card"><div class="sectionTitle">기업 선택</div><div class="pillRow">${rows.map(x=>`<button class="pill companyPick ${x.company===r.company?"on":""}" data-company="${esc(x.company)}">${esc(x.company)}</button>`).join("")}</div></section><section class="card">${kv("채용/사업 신호",r.signal)}${kv("기본정보",r.basic)}${kv("시장성",r.market)}${kv("평판 단서",r.review)}${kv("리스크",r.risk)}${kv("추천 영업멘트",r.talk)}${r.link?`<a class="link" href="${esc(String(r.link).split("\n")[0])}" target="_blank">근거 링크 열기</a>`:""}</section></main>`}
function sourcing(){return`<main class="grid"><section class="card"><div class="sectionTitle">소싱 루트북</div><p>직무별 X-ray 검색어를 바로 복사해서 리멤버·링크드인·구글에 적용합니다.</p><a class="link" href="/sourcing.html" target="_blank">새 창으로 열기</a></section><div class="sourceFrameWrap"><iframe title="소싱 루트북" src="/sourcing.html" class="sourceFrame"></iframe></div></main>`}
function candidate(){return`<main class="grid"><section class="card"><div class="sectionTitle">후보자 판단</div><p>추천사는 길게 쓰지 말고, 적합도·리스크·다음 행동만 봅니다.</p></section><section class="list">${(state.data.candidates||[]).map(r=>`<div class="item"><div class="row"><div><div class="company">${esc(r.name)}</div><div class="muted">${esc(r.role)}</div></div>${b("적합도 "+esc(r.fit)+"%",Number(r.fit)>=85?"good":"warn")}</div><div class="scoreBar"><i style="width:${Number(r.fit)||70}%"></i></div>${kv("리스크",r.risk)}${kv("다음 행동",r.action)}</div>`).join("")}</section></main>`}
function invest(){const rows=state.data.investments||[];return`<main class="grid"><section class="card hero"><div class="eyebrow">Investment Desk</div><h1>투자탭</h1><p>여기는 추천 매수/매도 신호가 아니라, 감정매매를 막는 가격선 체크용입니다.</p><div class="actionBox">원칙: 평단 회복 욕심보다 손실 확대 방어가 먼저</div></section><section class="grid3">${rows.map(r=>{const avg=Number(r.avg),cur=Number(r.cur);const pnl=avg&&cur?(((cur-avg)/avg)*100).toFixed(1):"-";return`<div class="card"><div class="row"><div><div class="company">${esc(r.name)}</div><div class="muted">${esc(r.type)}</div></div>${b(pnl==="-"?"체크":(Number(pnl)>=0?"+":"")+pnl+"%",pnl!=="-"&&Number(pnl)>=0?"good":"blue")}</div>${kv("평단",r.avg)}${kv("현재",r.cur)}${kv("판단",r.view)}<div class="actionBox">${esc(r.rule)}</div>${kv("오늘 행동",r.action)}</div>`}).join("")}</section></main>`}
function assistant(){return`<main class="grid"><section class="card hero"><div class="eyebrow">SJ Manager</div><h1>오늘은 실행 모드</h1><p>헤드헌터 수익은 시스템 완성도가 아니라 연락·추천·클로징에서 납니다.</p></section><section class="grid3">${(state.data.assistant||[]).map(x=>`<div class="card"><div class="sectionTitle">${esc(x.title)}</div><p>${esc(x.body)}</p></div>`).join("")}</section><section class="card"><div class="sectionTitle">5분 리셋</div><ol class="todo"><li>지금 당장 돈이 되는가?</li><li>후보가 실제로 있는가?</li><li>오늘 연락할 담당자가 있는가?</li><li>셋 중 하나라도 아니면 보류</li></ol></section></main>`}
function settings(){return`<main class="grid"><section class="card"><div class="sectionTitle">Google Sheets 연결</div><p>Apps Script 웹앱 URL을 넣으면 실제 시트 데이터로 바뀝니다.</p><textarea id="apiUrl" placeholder="https://script.google.com/macros/s/....../exec">${esc(state.apiUrl)}</textarea><button class="btn gold" id="saveApi">저장하고 연결</button></section><section class="card"><div class="sectionTitle">시트명 권장</div><ol class="todo"><li>오늘_영업판단</li><li>기업_원스탑</li><li>대안타깃_DB</li><li>후보자_DB</li><li>투자_체크</li></ol></section></main>`}
function render(note=""){const map={home,sales,company,sourcing,candidate,invest,assistant,settings};$("#app").innerHTML=layout((map[state.tab]||home)(),note);bind()}
function bind(){document.querySelectorAll("[data-tab]").forEach(el=>el.onclick=()=>{state.tab=el.dataset.tab;localStorage.setItem("sjone_tab",state.tab);render()});const r=$("#refreshBtn");if(r)r.onclick=refreshData;const save=$("#saveApi");if(save)save.onclick=()=>{state.apiUrl=$("#apiUrl").value.trim();localStorage.setItem("sjone_api_url",state.apiUrl);refreshData()};document.querySelectorAll(".companyItem").forEach(el=>el.onclick=()=>{state.selectedCompany=el.dataset.company;state.tab="company";localStorage.setItem("sjone_tab","company");render()});document.querySelectorAll(".companyPick").forEach(el=>el.onclick=()=>{state.selectedCompany=el.dataset.company;render()})}
async function refreshData(){if(!state.apiUrl){state.data=demo;render("Apps Script URL이 없어 데모 데이터로 표시 중입니다.");return}render("데이터 갱신 중...");try{const url=state.apiUrl+(state.apiUrl.includes("?")?"&":"?")+"type=dashboard&ts="+Date.now();const res=await fetch(url);if(!res.ok)throw new Error("API 응답 오류");const data=await res.json();state.data={...demo,...data};render("갱신 완료: "+new Date().toLocaleString("ko-KR"))}catch(e){render("연결 실패: "+e.message+" / Apps Script 웹앱 URL과 접근권한을 확인하세요.")}}
if("serviceWorker" in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("/sw.js").catch(()=>{}))}
render();
