import "./style.css";
const $=s=>document.querySelector(s);
const demo={updatedAt:new Date().toLocaleString("ko-KR"),live:false,daily:[{"결정":"오늘전화","회사명":"예시반도체","산업":"반도체","직무/포지션":"품질/해외영업","점수":"91","근거요약":"반도체 경력직 복수 채용 + 증설/수주 신호","추천액션":"담당자 찾기 → 전화/메일 동시","영업멘트":"최근 경력직 채용 신호를 확인했습니다. 적합 후보자 추천 가능성이 있어 짧게 논의드리고 싶습니다.","링크":"https://example.com"}],onestop:[{"회사명":"예시반도체","영업등급":"A","추천결정":"오늘전화","핵심공고/신호":"품질/해외영업 경력직 채용","기본정보 요약":"반도체 장비·소재 관련 기업. 상세 매출/고객사는 확인 필요.","시장평가/성장성":"증설·수주 키워드 감지.","재직자·경력자 평가 단서":"검색 단서 부족. 평판 추가 확인 필요.","리스크/거절가능성":"직접채용 가능성. 헤드헌팅 활용 여부 확인 필요.","접근전략":"채용난이도와 후보자 추천 가능성으로 접근.","추천 영업멘트":"관련 후보자 추천 가능성이 있어 짧게 논의드리고 싶습니다.","근거링크":"https://example.com"}],alt:[{"회사명":"대안소부장","산업":"반도체","추정직무":"품질","영업점수":"72","추천등급":"B-후보DB","수집근거":"소부장 경력 채용 감지","링크":"https://example.com"}],candidates:[{name:"김OO",role:"반도체 품질",fit:86,risk:"연봉/거리 확인 필요",action:"품질 포지션 우선 검토"},{name:"박OO",role:"자동화 SW",fit:78,risk:"독립수행 경험 확인",action:"장비 SW 후보로 보류풀"}],investments:[{name:"KODEX 코스닥150",category:"ETF",ticker:"229200",avg:16900,cur:null,pnlPct:null,judgment:"실시간 연결 전",rule:"Apps Script 연결 후 현재가 자동 반영",action:"설정에서 웹앱 URL 저장 후 갱신"},{name:"GME",category:"미국주식",ticker:"GME",avg:28.15,cur:null,pnlPct:null,judgment:"실시간 연결 전",rule:"Apps Script 연결 후 현재가 자동 반영",action:"설정에서 웹앱 URL 저장 후 갱신"},{name:"원/달러 환율",category:"환율",ticker:"USDKRW",avg:null,cur:null,pnlPct:null,judgment:"실시간 연결 전",rule:"환율 착시 주의",action:"설정에서 웹앱 URL 저장 후 갱신"}]};
const state={tab:localStorage.getItem("sjone_tab")||"home",apiUrl:localStorage.getItem("sjone_api_url")||"",data:demo,selectedCompany:null,loading:false};
const NAV=[["home","홈"],["sales","영업"],["company","기업360"],["sourcing","소싱"],["candidate","후보"],["investment","투자"],["assistant","비서"]];
const esc=x=>String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const num=x=>x==null||x===""||isNaN(Number(String(x).replace(/,/g,"")))?null:Number(String(x).replace(/,/g,""));
function badge(t,c="warn"){return `<span class="badge ${c}">${esc(t)}</span>`}function tone(d){d=String(d||"");return d.includes("오늘전화")?"bad":d.includes("오늘메일")?"warn":d.includes("접촉")?"good":""}function kv(k,v){return v?`<div class="kv"><b>${esc(k)}</b><span>${esc(v)}</span></div>`:""}
function layout(content,note=""){return `<div class="app"><header class="top"><div><div class="brand">SJ <b>ONE</b> PRODUCTION <span class="version">v3.2</span></div><div class="sub">영업 · 후보 · 소싱 · 투자 · 개인비서 통합 대시보드</div></div><div class="pillRow"><button class="btn" data-tab="settings">설정</button><button class="btn gold" id="refreshBtn">갱신</button></div></header>${note?`<div class="notice">${esc(note)}</div>`:""}${content}<nav class="bottom">${NAV.map(([k,l])=>`<button class="${state.tab===k?"on":""}" data-tab="${k}">${l}</button>`).join("")}</nav></div>`}
function stats(){const d=state.data||demo,dy=d.daily||[],os=d.onestop||[],alt=d.alt||[];return{call:dy.filter(x=>String(x["결정"]).includes("오늘전화")).length,mail:dy.filter(x=>String(x["결정"]).includes("오늘메일")).length,a:os.filter(x=>String(x["영업등급"]).includes("A")).length,alt:alt.length}}
function salesCard(r){return `<div class="item companyItem" data-company="${esc(r["회사명"]||"")}"><div class="row"><div><div class="company">${esc(r["회사명"]||"회사명 확인필요")}</div><div class="muted">${esc(r["산업"]||"")} · ${esc(r["직무/포지션"]||"")}</div></div>${badge(r["결정"]||"판단",tone(r["결정"]))}</div><p>${esc(r["근거요약"]||"")}</p><div class="actionBox">${esc(r["추천액션"]||"")}</div>${r["영업멘트"]?`<details><summary>영업멘트</summary><p>${esc(r["영업멘트"])}</p></details>`:""}${r["링크"]?`<a class="link" href="${esc(r["링크"])}" target="_blank">근거 열기</a>`:""}</div>`}
function home(){const d=state.data||demo,dy=d.daily||[],top=dy[0]||{},s=stats();return `<main class="grid"><section class="card hero"><div class="eyebrow">오늘의 최우선 판단</div><h1>${esc(top["회사명"]||"오늘 영업판단 생성 필요")}</h1><div class="row"><div>${badge(top["결정"]||"대기",tone(top["결정"]))}</div><span class="muted">점수 ${esc(top["점수"]||"-")}</span></div><p>${esc(top["근거요약"]||"Apps Script URL 연결 후 갱신하세요.")}</p><div class="actionBox">${esc(top["추천액션"]||"오늘_영업판단과 기업_원스탑 2개만 보고 움직이세요.")}</div></section><section class="grid4"><div class="card"><div class="metric">${s.call}</div><div class="label">오늘 전화</div></div><div class="card"><div class="metric">${s.mail}</div><div class="label">오늘 메일</div></div><div class="card"><div class="metric">${s.a}</div><div class="label">A등급 기업</div></div><div class="card"><div class="metric">${s.alt}</div><div class="label">대안 타깃</div></div></section><section class="card"><div class="sectionTitle">오늘 할 일</div><ol class="todo"><li>오늘전화 기업 TOP부터 연락</li><li>기업360에서 리스크 확인</li><li>담당자 찾기 → 짧은 메일/전화</li><li>거절 시 대안타깃_DB B등급 이상으로 이동</li></ol></section><section class="card"><div class="sectionTitle">오늘 영업 TOP5</div><div class="list">${dy.slice(0,5).map(salesCard).join("")}</div></section></main>`}
function sales(){return `<main class="grid"><section class="card"><div class="sectionTitle">Sales Radar — 오늘_영업판단</div><p>오늘 전화/메일할 기업만 봅니다.</p></section><section class="list">${(state.data.daily||[]).map(salesCard).join("")||`<div class="card">데이터 없음</div>`}</section></main>`}
function company(){const rows=state.data.onestop||[],sel=state.selectedCompany||(rows[0]&&rows[0]["회사명"]),r=rows.find(x=>x["회사명"]===sel)||rows[0];if(!r)return `<main class="grid"><div class="card">기업_원스탑 데이터 없음</div></main>`;return `<main class="grid"><section class="card hero"><div class="row"><div><div class="eyebrow">Company 360</div><h1>${esc(r["회사명"])}</h1></div>${badge((r["영업등급"]||"-")+" · "+(r["추천결정"]||"-"),String(r["영업등급"]).includes("A")?"bad":"warn")}</div><div class="actionBox">${esc(r["접근전략"]||"접근전략 없음")}</div></section><section class="card"><div class="sectionTitle">기업 선택</div><div class="pillRow">${rows.slice(0,20).map(x=>`<button class="btn small companyPick" data-company="${esc(x["회사명"])}">${esc(x["회사명"])}</button>`).join("")}</div></section><section class="card">${kv("핵심공고/신호",r["핵심공고/신호"])}${kv("기본정보",r["기본정보 요약"])}${kv("시장평가",r["시장평가/성장성"])}${kv("평판단서",r["재직자·경력자 평가 단서"])}${kv("리스크",r["리스크/거절가능성"])}${kv("추천 영업멘트",r["추천 영업멘트"])}${r["근거링크"]?`<a class="link" href="${esc(String(r["근거링크"]).split("\\n")[0])}" target="_blank">근거 링크 열기</a>`:""}</section></main>`}
function sourcing(){return `<main class="grid"><section class="card"><div class="sectionTitle">SJ 소싱 루트북</div><a class="link" href="/sourcing.html" target="_blank">새 창으로 크게 열기</a></section><div class="sourceFrameWrap"><iframe title="SJ 소싱 루트북" src="/sourcing.html" class="sourceFrame"></iframe></div></main>`}
function candidate(){const rows=state.data.candidates||demo.candidates;return `<main class="grid"><section class="card"><div class="sectionTitle">Candidate AI</div><p>후보자는 적합도·리스크·추천 액션만 봅니다.</p></section><section class="list">${rows.map(r=>`<div class="item"><div class="row"><div><div class="company">${esc(r.name)}</div><div class="muted">${esc(r.role)}</div></div>${badge("적합도 "+esc(r.fit)+"%",Number(r.fit)>=85?"good":"warn")}</div>${kv("리스크",r.risk)}${kv("추천액션",r.action)}</div>`).join("")}</section></main>`}
function investment(){const inv=state.data.investments||demo.investments;return `<main class="grid"><section class="card hero"><div class="eyebrow">Investment Desk</div><h1>투자탭</h1><p>추천 매수/매도가 아니라 감정매매 차단용 가격 체크입니다.</p><div class="actionBox">${state.data.live?"실시간 연결됨: "+esc(state.data.updatedAt):"실시간 연결 전: 설정에서 Apps Script 웹앱 URL 저장 후 갱신"}</div></section><section class="grid3">${inv.map(investCard).join("")}</section></main>`}
function investCard(x){const cur=num(x.cur),avg=num(x.avg),p= x.pnlPct!=null?Number(x.pnlPct):(cur!=null&&avg?((cur-avg)/avg*100):null);const pc=p==null?"-":(p>=0?"+":"")+p.toFixed(2)+"%";return `<div class="card"><div class="row"><div><div class="company">${esc(x.name)}</div><div class="muted">${esc(x.category||x.ticker||"")}</div></div>${badge(pc,p==null?"":p>=0?"good":"bad")}</div><table class="table"><tbody><tr><th>평단</th><td>${avg?avg.toLocaleString():"-"}</td></tr><tr><th>현재</th><td>${cur?cur.toLocaleString():"체크필요"}</td></tr><tr><th>판단</th><td>${esc(x.judgment||"")}</td></tr></tbody></table><div class="actionBox">${esc(x.rule||"")}</div>${kv("오늘 행동",x.action)}${kv("출처",x.source)}</div>`}
function assistant(){return `<main class="grid"><section class="card hero"><div class="eyebrow">SJ Assistant</div><h1>오늘은 실행 우선</h1><p>시스템 수정은 하루 1회, 영업 행동은 즉시 실행.</p><div class="actionBox">1순위 오늘전화 → 2순위 기업360 → 3순위 후보 제안</div></section><section class="card"><div class="sectionTitle">운영 원칙</div><ol class="todo"><li>SJ ONE은 하루 2회만 확인</li><li>시트는 오늘_영업판단 / 기업_원스탑만 보기</li><li>새 기능 추가는 월 1회 이하</li><li>매출과 직접 관련 없는 자동화는 보류</li></ol></section></main>`}
function settings(){return `<main class="grid"><section class="card"><div class="sectionTitle">Google Sheets / Apps Script 연결</div><p>Apps Script 웹앱 URL을 붙여넣고 저장하세요.</p><textarea id="apiUrl" placeholder="https://script.google.com/macros/s/....../exec">${esc(state.apiUrl)}</textarea><div style="height:10px"></div><button class="btn gold" id="saveApi">저장하고 연결</button></section><section class="card"><div class="sectionTitle">연결 후 작동</div><ol class="todo"><li>투자탭: KODEX / GME / 원달러 환율 현재가 반영</li><li>영업탭: 오늘_영업판단 시트 반영</li><li>기업360: 기업_원스탑 시트 반영</li></ol></section></main>`}
function jsonp(url){return new Promise((resolve,reject)=>{const cb="__sjone_cb_"+Date.now()+"_"+Math.floor(Math.random()*1e6);const s=document.createElement("script");window[cb]=d=>{delete window[cb];s.remove();resolve(d)};s.onerror=()=>{delete window[cb];s.remove();reject(new Error("JSONP 연결 실패"))};s.src=url+(url.includes("?")?"&":"?")+"callback="+cb+"&ts="+Date.now();document.body.appendChild(s);setTimeout(()=>{if(window[cb]){delete window[cb];s.remove();reject(new Error("응답 시간초과"))}},15000)})}
async function refreshData(){if(!state.apiUrl){state.data=demo;render("Apps Script URL 없음: 데모 데이터 표시 중");return}render("데이터 갱신 중...");try{const data=await jsonp(state.apiUrl);state.data={...demo,...data,live:true};render("갱신 완료: "+new Date().toLocaleString("ko-KR"))}catch(e){state.data=demo;render("연결 실패: "+e.message)}}
function render(note=""){const map={home,sales,company,sourcing,candidate,investment,assistant,settings};$("#app").innerHTML=layout((map[state.tab]||home)(),note);bind()}function bind(){document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;if(state.tab==="sourcing"){localStorage.setItem("sjone_tab","home");location.href="/sourcing.html";return;}localStorage.setItem("sjone_tab",state.tab);localStorage.setItem("sjone_tab",state.tab);render()});const r=$("#refreshBtn");if(r)r.onclick=refreshData;const sv=$("#saveApi");if(sv)sv.onclick=()=>{state.apiUrl=$("#apiUrl").value.trim();localStorage.setItem("sjone_api_url",state.apiUrl);refreshData()};document.querySelectorAll(".companyItem").forEach(el=>el.onclick=()=>{state.selectedCompany=el.dataset.company;state.tab="company";localStorage.setItem("sjone_tab","company");render()});document.querySelectorAll(".companyPick").forEach(el=>el.onclick=()=>{state.selectedCompany=el.dataset.company;render()})}
if("serviceWorker" in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("/sw.js").catch(()=>{}))}render();if(state.apiUrl)refreshData();
