import "./style.css";
const $=s=>document.querySelector(s);const demo={daily:[{"결정":"오늘전화","회사명":"예시반도체","산업":"반도체","직무/포지션":"품질/해외영업","점수":"91","근거요약":"반도체 경력직 복수 채용 + 최근 증설 뉴스 감지","추천액션":"담당자 찾기 → 전화/메일 동시","영업멘트":"최근 경력직 채용 신호를 확인했습니다.","링크":"https://example.com"},{"결정":"오늘메일","회사명":"AI인프라테크","산업":"AI데이터센터","직무/포지션":"전장제어/SW","점수":"82","근거요약":"AI 데이터센터 인프라 투자 및 경력 채용 감지","추천액션":"담당자 확인 후 짧은 제안메일","영업멘트":"AI 인프라 경력직 채용 관련 후보자 추천 가능성이 있습니다.","링크":"https://example.com"}],onestop:[{"회사명":"예시반도체","영업등급":"A","추천결정":"오늘전화","핵심공고/신호":"품질/해외영업 경력직 채용","기본정보 요약":"반도체 장비·소재 관련 기업으로 추정.","시장평가/성장성":"증설/수주 키워드가 있어 성장 신호가 감지됨.","재직자·경력자 평가 단서":"검색 스니펫만으로 확정 불가.","리스크/거절가능성":"직접채용으로 충원 가능성.","접근전략":"경력직 채용난이도를 먼저 언급하고 접근.","추천 영업멘트":"최근 경력직 채용 신호를 확인했습니다.","근거링크":"https://example.com"}],alt:[{"회사명":"대안소부장","산업":"반도체","추정직무":"품질","영업점수":"72","추천등급":"B-후보DB","수집근거":"소부장 경력 채용 감지"}],candidates:[{name:"김OO",role:"반도체 품질",fit:86,risk:"연봉/거리 확인 필요",action:"소부장 품질 포지션 우선 검토"}],investments:[{name:"KODEX 코스닥150",cur:15240,avg:16900,rule:"14,365원 이탈 시 절반축소"}]};
const state={tab:localStorage.getItem('sjone_tab')||'home',data:demo,apiUrl:localStorage.getItem('sjone_api_url')||'',selectedCompany:null};const NAV=[["home","홈"],["sales","영업"],["company","기업360"],["sourcing","소싱"],["candidate","후보"],["assistant","비서"]];
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function badge(t,c='warn'){return `<span class="badge ${c}">${esc(t)}</span>`}function tone(d){d=String(d||'');if(d.includes('오늘전화'))return'bad';if(d.includes('접촉'))return'good';return'warn'}function kv(k,v){return v?`<div class="kv"><b>${esc(k)}</b><span>${esc(v)}</span></div>`:''}
function layout(c,n=''){return `<div class="app"><header class="top"><div><div class="brand">SJ <span>ONE</span> PRODUCTION</div><div class="sub">월 3,000만원 목표용 · 헤드헌팅 우선순위 OS</div></div><div><button class="btn" data-tab="settings">설정</button> <button class="btn gold" id="refreshBtn">갱신</button></div></header>${n?`<div class="notice">${esc(n)}</div>`:''}${c}<nav class="bottom">${NAV.map(([k,l])=>`<button class="${state.tab===k?'on':''}" data-tab="${k}">${l}</button>`).join('')}</nav></div>`}
function stats(){let d=state.data,dy=d.daily||[],os=d.onestop||[],alt=d.alt||[];return{call:dy.filter(x=>String(x['결정']).includes('오늘전화')).length,mail:dy.filter(x=>String(x['결정']).includes('오늘메일')).length,a:os.filter(x=>String(x['영업등급']).includes('A')).length,alt:alt.length}}
function salesCard(r){return `<div class="item companyItem" data-company="${esc(r['회사명']||'')}"><div class="row"><div><div class="company">${esc(r['회사명']||'회사명 확인필요')}</div><div class="muted">${esc(r['산업']||'')} · ${esc(r['직무/포지션']||'')}</div></div>${badge(r['결정']||'판단',tone(r['결정']))}</div><p>${esc(r['근거요약']||'')}</p><div class="actionBox">${esc(r['추천액션']||'')}</div>${r['링크']?`<a class="link" href="${esc(r['링크'])}" target="_blank">근거 열기</a>`:''}</div>`}
function home(){let d=state.data,dy=d.daily||[],top=dy[0]||{},s=stats();return `<main class="grid"><section class="card hero"><div class="eyebrow">오늘의 최우선 판단</div><h1>${esc(top['회사명']||'오늘 영업판단 생성 필요')}</h1><div class="row">${badge(top['결정']||'대기',tone(top['결정']))}<span class="muted">점수 ${esc(top['점수']||'-')}</span></div><p>${esc(top['근거요약']||'Google Sheets에서 원스톱 전체 갱신 후 운영모드를 실행하세요.')}</p><div class="actionBox">${esc(top['추천액션']||'오늘_영업판단과 기업_원스탑 2개만 보고 움직이세요.')}</div></section><section class="grid4"><div class="card"><div class="metric">${s.call}</div><div class="label">오늘 전화</div></div><div class="card"><div class="metric">${s.mail}</div><div class="label">오늘 메일</div></div><div class="card"><div class="metric">${s.a}</div><div class="label">A등급 기업</div></div><div class="card"><div class="metric">${s.alt}</div><div class="label">대안 타깃</div></div></section><section class="card"><div class="sectionTitle">오늘 할 일</div><ol class="todo"><li>오늘전화 기업 TOP부터 연락</li><li>기업360에서 리스크 확인</li><li>담당자 찾기 → 짧은 메일/전화</li><li>시스템 수정 금지. 영업 실행 우선</li></ol></section><section class="card"><div class="sectionTitle">오늘 영업 TOP5</div><div class="list">${dy.slice(0,5).map(salesCard).join('')}</div></section></main>`}
function sales(){let dy=state.data.daily||[];return `<main class="grid"><section class="card"><div class="sectionTitle">Sales Radar</div><p>오늘 전화/메일할 기업만 봅니다.</p></section><section class="list">${dy.map(salesCard).join('')}</section></main>`}
function company(){let rows=state.data.onestop||[],r=rows[0];if(!r)return `<main class="grid"><div class="card">기업_원스탑 데이터 없음</div></main>`;return `<main class="grid"><section class="card hero"><div class="row"><div><div class="eyebrow">Company 360</div><h1>${esc(r['회사명'])}</h1></div>${badge((r['영업등급']||'-')+' · '+(r['추천결정']||'-'),'bad')}</div><div class="actionBox">${esc(r['접근전략']||'접근전략 없음')}</div></section><section class="card">${kv('핵심공고/신호',r['핵심공고/신호'])}${kv('기본정보',r['기본정보 요약'])}${kv('시장평가',r['시장평가/성장성'])}${kv('리스크',r['리스크/거절가능성'])}${kv('추천 영업멘트',r['추천 영업멘트'])}</section></main>`}
function sourcing(){return `<main class="grid"><section class="card"><div class="sectionTitle">SJ 소싱 루트북</div><a class="link" href="/sourcing.html" target="_blank">새 창으로 크게 열기</a></section><div class="sourceFrameWrap"><iframe title="SJ 소싱 루트북" src="/sourcing.html" class="sourceFrame"></iframe></div></main>`}
function candidate(){let rows=state.data.candidates||demo.candidates;return `<main class="grid"><section class="card"><div class="sectionTitle">Candidate AI</div><p>후보자는 적합도·리스크·추천 액션만 봅니다.</p></section><section class="list">${rows.map(r=>`<div class="item"><div class="row"><div><div class="company">${esc(r.name)}</div><div class="muted">${esc(r.role)}</div></div>${badge('적합도 '+esc(r.fit)+'%','good')}</div>${kv('리스크',r.risk)}${kv('추천액션',r.action)}</div>`).join('')}</section></main>`}
function assistant(){return `<main class="grid"><section class="card hero"><div class="eyebrow">SJ Assistant</div><h1>오늘은 시스템 수정 금지</h1><p>오늘의 목표는 앱 개선이 아니라 영업 실행입니다.</p><div class="actionBox">오늘전화 기업 처리 → 기업360 확인 → 후보자 제안</div></section></main>`}
function settings(){return `<main class="grid"><section class="card"><div class="sectionTitle">Google Sheets 연결</div><textarea id="apiUrl" placeholder="https://script.google.com/macros/s/....../exec">${esc(state.apiUrl)}</textarea><button class="btn gold" id="saveApi">저장하고 연결</button></section></main>`}
function render(note=''){let c=state.tab==='home'?home():state.tab==='sales'?sales():state.tab==='company'?company():state.tab==='sourcing'?sourcing():state.tab==='candidate'?candidate():state.tab==='assistant'?assistant():settings();$('#app').innerHTML=layout(c,note);bind()}function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;localStorage.setItem('sjone_tab',state.tab);render()});if($('#refreshBtn'))$('#refreshBtn').onclick=refreshData;if($('#saveApi'))$('#saveApi').onclick=()=>{state.apiUrl=$('#apiUrl').value.trim();localStorage.setItem('sjone_api_url',state.apiUrl);refreshData()}}
async function refreshData(){if(!state.apiUrl){state.data=demo;render('Apps Script 웹앱 URL이 없어 데모 데이터로 표시 중입니다.');return}render('데이터 갱신 중...');try{let url=state.apiUrl+(state.apiUrl.includes('?')?'&':'?')+'type=dashboard&ts='+Date.now();let res=await fetch(url);if(!res.ok)throw new Error('API 응답 오류');state.data=await res.json();render('갱신 완료')}catch(e){render('연결 실패: '+e.message)}}
if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}))}render();